### ISSUE TITLE
iOS - System.InvalidOperationException: The application is not configured yet

### ISSUE THREAD

**Issue by manuelcosta74** [xamarin/urho#157] opened 2016-10-05 22:55 UTC
@EgorBo , in iOS, if we put a break point after creating an instance of an application we will always end up with the following crash when Run is called

System.InvalidOperationException: The application is not configured yet
  at Urho.Application.get_Current () [0x00010] in <a6902141f5044aee89324c2daf528fc1>:0 
  at Urho.Application.InvokeOnMain (System.Action action) [0x00000] in <a6902141f5044aee89324c2daf528fc1>:0 
  at Urho.RefCounted.Finalize () [0x00027] in <a6902141f5044aee89324c2daf528fc1>:0 

This looks like a RefCounted object being GC collected after an Application instance creation.
 
This is possible to reproduce in FeatureSample

var application = Urho.Application.CreateInstance(type, new ApplicationOptions("Data"));
//Put a breakpoint in run
application.Run();

cheers
Manuel

**Comment by EgorBo** [comment] 2016-10-05 23:08
@manuelcosta74 Does it happen on a very first app instance creation? I mean it looks like some RefCounted was collected before Current property was set (I am wondering which type it has). Let me try to reproduce.

**Comment by EgorBo** [comment] 2016-10-05 23:20
oops, the issue was closed by a comment "it doesn't fix" 😄

**Comment by manuelcosta74** [comment] 2016-10-05 23:28
@EgorBo  i think this is related with Context instance. If you create an instance through 
public Application(ApplicationOptions options)

it creates a new Context()

 public Application(ApplicationOptions options) : this(new Context(), options) {} 

In the constructor you do increase refcount, but you do not keep a reference on c# side ending up being GC claimed. 
I think that a generic solution to prevent this type of issues is to keep a manage reference when you do RefCounted.AddRef() and remove it when counter is 0.

Manuel

**Comment by EgorBo** [comment] 2016-10-05 23:32
@manuelcosta74 
new Context() invokes RegisterObject (so it will be added to a globale cache as a weakref).
usually, AddRef() leads to a native-to-managed callback that will promote an object in the cache to a strong reference.

**Comment by EgorBo** [comment] 2016-10-05 23:32
but yes, Contest is the first suspect here.

**Comment by manuelcosta74** [comment] 2016-10-06 00:10
ok, so it can be something like Runtime.Cleanup(); 

Application calls it in ProxyStop and this method is passed to ApplicationProxy_ApplicationProxy, which means that native side can call stop callback somewhere on the initialisation process;

**Comment by EgorBo** [comment] 2016-10-09 00:14
Should be fixed now with https://github.com/xamarin/urho/commit/94b415fbb33bcabfc411bb9d46ab440ee7471e4c I'll test & close with the next nuget update candidate this.

**Comment by EgorBo** [comment] 2016-10-16 20:52
Fixed.

**Closed by EgorBo** 2016-10-16 20:52 UTC
