### ISSUE TITLE
Accented character support for Win Desktop

### ISSUE THREAD

**Issue by Yorgl** [xamarin/urho#179] opened 2017-01-06 21:40 UTC
Hello all,

I'm new to it but I'm very happy with UrhoSharp. I think its a great API ! I'm using version 1.2.21.
Here is my issue : when I load some ttf files on which accented characters are defined, theses characters (like é à ù...) are replaced with "?" on Desktop. These characters are well rendered on Android.

This problem can easily be reproduced with the HelloWorld sample, changing the font. I tried with many fonts downloaded from internet, this issue is always happening.
Thank you for your help.

Yann

**Comment by migueldeicaza** [comment] 2017-01-10 01:39
This looks like a duplicate of #161

**Closed by migueldeicaza** 2017-01-10 01:39 UTC

**Comment by Yorgl** [comment] 2017-01-19 20:32
Indeed ! Sorry for that :s
