### ISSUE TITLE
RunActionsAsync never executes 

### ISSUE THREAD

**Issue by elios264** [xamarin/urho#129] opened 2016-07-01 00:21 UTC
This is the minimal example: 

		protected override async void Start()
		{
            scene = new Scene();

            var node = scene.CreateChild();

            await node.RunActionsAsync(new EaseIn(new MoveBy(1f, new Vector3(-10, -2, -10)), 1));

            //node.Remove();

            await scene.CreateChild().RunActionsAsync(new EaseOut(new MoveBy(0.5f, new Vector3(0, 3, 0)), 1));

            Urho.IO.Log.Write(LogLevel.Error, "Never hit if node.Remove(); uncomented");
        }

The EaseOut in the second await will never be executed if

            //node.Remove();

is uncommented, not sure if this is a Urhosharp bug or Urho3d bug :-(

**Comment by EgorBo** [comment] 2016-07-01 06:06
@elios264 which version of UrhoSharp do you use? I can't reproduce it with 1.0.557.

**Comment by elios264** [comment] 2016-07-01 13:56
@EgorBo I'm using:  
`<package id="UrhoSharp" version="1.0.557" targetFramework="net45" />`

this is the console app: 

```
using Urho;
using Urho.Actions;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            new UrhoBug().Run();
        }
    }

    class UrhoBug : Application
    {
        protected override async void Start()
        {
            var scene = new Scene();

            var node = scene.CreateChild();
            await node.RunActionsAsync(new EaseIn(new MoveBy(1f, new Vector3(-10, -2, -10)), 1));
            node.Remove();
            await scene.CreateChild().RunActionsAsync(new EaseOut(new MoveBy(0.5f, new Vector3(0, 3, 0)), 1));

            Urho.IO.Log.Write(LogLevel.Error, "Never logged");
        }
    }
}

```

Just set a breakpoint in the Urho.IO.Log.Write, and it'll never be hit.

**Comment by Therzok** [comment] 2016-07-01 18:04
From my research, it's apparently not calling `CallFunc`'s `Execute` method. The `Stop` method that's called on cancelling a task ends up calling the `Stop` method, which does not set the `TaskCompletionSource` result.

**Comment by Therzok** [comment] 2016-07-01 18:07
The bug is fixed with this patch, but not sure of the implications of doing stop on a sequence that doesn't come from a chained internal sequence for actions.

```diff
diff --git a/Bindings/Portable/Actions/Instants/Callfunc/CallFunc.cs b/Bindings/Portable/Actions/Instants/Callfunc/CallFunc.cs
index 0147b10..57d061d 100644
--- a/Bindings/Portable/Actions/Instants/Callfunc/CallFunc.cs
+++ b/Bindings/Portable/Actions/Instants/Callfunc/CallFunc.cs
@@ -45,6 +45,11 @@ namespace Urho.Actions
 		{
 			CallFunction?.Invoke();
 		}
+	
+		internal protected override void Stop()
+		{
+			CallFunction?.Invoke();
+		}
 
 		public override void Update (float time)
 		{
diff --git a/Urho.Tests/Actions/ActionManager.cs b/Urho.Tests/Actions/ActionManager.cs
index 561aa41..2a0d40f 100644
--- a/Urho.Tests/Actions/ActionManager.cs
+++ b/Urho.Tests/Actions/ActionManager.cs
@@ -34,6 +34,25 @@ namespace Urho.Tests
 
 			await app.Exit();
 		}
+
+		[Test]
+		public async Task TestIssue129()
+		{
+
+			var app = await Task.Run(() => SimpleApplication.RunAsync(1, 1));
+
+			var scene = new Scene();
+			var node = scene.CreateChild();
+			await node.RunActionsAsync(new EaseIn(new MoveBy(1f, new Vector3(-10, -2, -10)), 1));
+
+			node.Remove();
+
+			await scene.CreateChild().RunActionsAsync(new EaseOut(new MoveBy(0.5f, new Vector3(0, 3, 0)), 1));
+
+			Urho.IO.Log.Write(LogLevel.Error, "Never hit if node.Remove(); uncomented");
+
+			await app.Exit();
+		}
 	}
 }
```

**Comment by Therzok** [comment] 2016-07-01 18:08
So maybe there is a need for a custom Sequence subclass that's used internally by ActionManager to decide whether we should stop or execute the completion source setting.

**Closed** 2016-07-02 07:58 UTC
